In [3]:
import pandas as pd
import numpy as np
import string
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [4]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |  

True

In [19]:
# Sample Data

data = [
    {'message': 'i like the movie', 'sentiment': 'positive'},
    {'message': 'movie is not good', 'sentiment': 'negative'},
    {'message': 'wasted my time', 'sentiment': 'negative'},
    {'message': 'liked the movie', 'sentiment': 'positive'}
]

In [20]:
df = pd.DataFrame(data)
df

,message,sentiment
0,i like the movie,positive
1,movie is not good,negative
2,wasted my time,negative
3,liked the movie,positive


In [7]:
stop_Words = set(stopwords.words('english'))
stop_Words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [8]:
lemmatizer = WordNetLemmatizer()

In [21]:
# Convert text data into numerical. Build Corpus

In [22]:
def process_text(text):
  text = text.lower()
  text = ''.join([char for char in text if char not in string.punctuation])
  tokens = word_tokenize(text)
  tokens = [word for word in tokens if word.isalpha()]
  tokens = [word for word in tokens if word not in stop_Words]
  tokens = [lemmatizer.lemmatize(word) for word in tokens]
  return ' '.join(tokens)

In [23]:
df['tokens'] = df['message'].apply(process_text)

In [24]:
df

,message,sentiment,tokens
0,i like the movie,positive,like movie
1,movie is not good,negative,movie good
2,wasted my time,negative,wasted time
3,liked the movie,positive,liked movie


In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
vectorize = CountVectorizer() # Build the Corpus
X = vectorize.fit_transform(df['tokens'])
print(vectorize.get_feature_names_out())
print(X.toarray())

['good' 'like' 'liked' 'movie' 'time' 'wasted']
[[0 1 0 1 0 0]
 [1 0 0 1 0 0]
 [0 0 0 0 1 1]
 [0 0 1 1 0 0]]


In [27]:
y = df['sentiment'].map({'positive': 1, 'negative': 0})
y

,sentiment
0,1
1,0
2,0
3,1


In [28]:
model = LogisticRegression()
model.fit(X, y)
model.score(X, y)

1.0

In [29]:
test_message = 'movie is not good'
test_message = process_text(test_message)
test_message

'movie good'

In [30]:
test_data = vectorize.transform([test_message])
test_data

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (1, 6)>

In [31]:
model.predict(test_data)

array([0])

In [39]:
positive_message = 'liked the movie'
positive_message = process_text(positive_message)
positive_message

'liked movie'

In [40]:
positive_test_data = vectorize.transform([positive_message])
positive_test_data

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (1, 6)>

In [41]:
model.predict(positive_test_data)

array([1])

CountVectorize is an old technique. Also, with such little data you cannot predict properly.


*   TFID
*   Chatgpt Embeddings -> Latest.


In [42]:
# Using spacy instead of nltk
df = pd.DataFrame(data)
df

,message,sentiment
0,i like the movie,positive
1,movie is not good,negative
2,wasted my time,negative
3,liked the movie,positive


In [43]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [46]:
def preprocess(text):
  doc = nlp(text.lower())
  tokens = [token.lemma_ for token in doc if not token.is_punct and not token.is_stop]
  return ' '.join(tokens)

In [47]:
df['tokens'] = df['message'].apply(preprocess)
df

,message,sentiment,tokens
0,i like the movie,positive,like movie
1,movie is not good,negative,movie good
2,wasted my time,negative,waste time
3,liked the movie,positive,like movie


In [48]:
vectorize = CountVectorizer()
X = vectorize.fit_transform(df['tokens'])
print(vectorize.get_feature_names_out())
print(X.toarray())

['good' 'like' 'movie' 'time' 'waste']
[[0 1 1 0 0]
 [1 0 1 0 0]
 [0 0 0 1 1]
 [0 1 1 0 0]]


In [49]:
from sklearn.svm import SVC
svc = SVC()

In [50]:
test_data = vectorize.transform([test_message])
test_data

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (1, 5)>

In [52]:
svc.fit(X, y)

SVC()

In [53]:
svc.predict(test_data)

array([0])

In [54]:
# Discording not for sentiment
data = [
    {'message': 'i like the movie', 'sentiment': 'positive'},
    {'message': 'movie is not good', 'sentiment': 'negative'},
    {'message': 'wasted my time', 'sentiment': 'negative'},
    {'message': 'liked the movie', 'sentiment': 'positive'}
]


In [55]:
df = pd.DataFrame(data)
df

,message,sentiment
0,i like the movie,positive
1,movie is not good,negative
2,wasted my time,negative
3,liked the movie,positive


In [59]:
stop_Words = set(stopwords.words('english'))
stop_Words.discard('not')
lemmatizer = WordNetLemmatizer()

In [61]:
stop_Words_total = ', '.join(stop_Words)
stop_Words_total

"having, themselves, they, couldn't, where, t, which, m, we, too, yourselves, up, you, don, of, few, should've, shan't, nor, we're, over, won't, were, all, itself, against, some, if, yours, while, y, below, ours, her, any, so, i'll, i, whom, at, because, you've, are, how, has, haven, weren't, it, ve, himself, he, they'll, will, out, ourselves, didn, what, than, a, to, now, during, only, yourself, was, who, in, between, they've, is, the, you'd, myself, there, after, mightn, needn't, does, she, she's, shan, shouldn't, me, most, down, am, didn't, i'm, our, ma, through, then, isn't, such, aren, won, above, she'll, before, those, doing, theirs, more, wouldn't, re, weren, had, haven't, from, here, again, until, him, she'd, your, no, it's, further, you'll, aren't, we've, about, do, doesn't, other, his, hers, that, it'll, their, o, can, these, both, shouldn, they're, i've, very, hadn, wasn, we'd, did, we'll, he'll, hasn't, you're, have, ain, it'd, under, wouldn, or, why, them, isn, into, my, m

In [60]:
df['tokens'] = df['message'].apply(process_text)
df

,message,sentiment,tokens
0,i like the movie,positive,like movie
1,movie is not good,negative,movie not good
2,wasted my time,negative,wasted time
3,liked the movie,positive,liked movie
