Slicing

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8])

In [3]:
print(a[:3])

[1 2 3]


In [4]:
print(a[:3:2])

[1 3]


In [6]:
print(a[::2]) # Lower limit defaults to 0, Upper limit is the max which is index 9 as there are 9 elements and then step size of two

[1 3 5 7]


In [7]:
print(a[-3:]) #Last three numbers

[6 7 8]


In [8]:
# OR positive index
print(a[5:])

[6 7 8]


In [9]:
# Matrix

In [10]:
b = np.arange(1, 13).reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
b[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [12]:
b[1:, 1:3] # Takes row 1 till max row - 1, column 1 till 3-1

array([[ 6,  7],
       [10, 11]])

In [14]:
b[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [13]:
b[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [15]:
b[2,1:3]

array([10, 11])

In [ ]:
b[2,1]

In [16]:
b[2]

array([ 9, 10, 11, 12])

In [21]:
b[-1]

array([ 9, 10, 11, 12])

In [22]:
b[:, -1]

array([ 4,  8, 12])

In [ ]:
# Tensor

In [26]:
c = np.arange(1,37).reshape(3,3,4)

In [27]:
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [28]:
print(c[1,1,:])

[17 18 19 20]


In [29]:
print(c[0]) # same as c[0,:, :] or c[0,:]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
print(c[2, 0:2,1:3])

[[26 27]
 [30 31]]


In [33]:
d = np.arange(3*4*5).reshape(3,4,5)
print(d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [34]:
print(d[0,::2,:]) # First Matrix, then row 0, row 2. and then all columns

[[ 0  1  2  3  4]
 [10 11 12 13 14]]


In [35]:
print(d[2,:,::2])

[[40 42 44]
 [45 47 49]
 [50 52 54]
 [55 57 59]]


In [36]:
print(d[2,:,2::2])

[[42 44]
 [47 49]
 [52 54]
 [57 59]]


# Scipy build on top of numpy

In [37]:
!pip install gradio

In [38]:
import gradio as gr

In [39]:
def add_numbers(a,b):
  return a + b

demo = gr.Interface(fn=add_numbers, inputs=['number', 'number'], outputs='text')
demo.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://bd8ae862ddb6f8992f.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
