In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])

In [ ]:
print(a)

[1 2 3 4 5 6 7 8]


In [ ]:
print(a[:3])

[1 2 3]


In [ ]:
print(a[:3:2])

[1 3]


In [ ]:
print(a[::2])

[1 3 5 7]


In [ ]:
print(a[-3:])

[6 7 8]


In [ ]:
print(a[5:])

[6 7 8]


In [ ]:
b = np.arange(1,13).reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
b[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [ ]:
b[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [ ]:
b[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b[1:3,2:4]

array([[ 7,  8],
       [11, 12]])

In [ ]:
b[2,1:3]

array([10, 11])

In [ ]:
b[2]

array([ 9, 10, 11, 12])

In [ ]:
b[-1]

array([ 9, 10, 11, 12])

In [ ]:
b[:,-1]

array([ 4,  8, 12])

In [ ]:
b.shape[0]

3

In [ ]:
b.shape[1]

4

In [ ]:
b[:,b.shape[1]-1]

array([ 4,  8, 12])

In [ ]:
c = np.arange(1,37).reshape(3,3,4)
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [ ]:
print(c[1,1,:])

[17 18 19 20]


In [ ]:
print(c[1,1])

[17 18 19 20]


In [ ]:
print(c[2])

[[25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]]


In [ ]:
d = np.arange(3*4*5).reshape(3,4,5)
print(d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [ ]:
print(d[0,::2,:])

[[ 0  1  2  3  4]
 [10 11 12 13 14]]


In [ ]:
print(d[2,:,::2])

[[40 42 44]
 [45 47 49]
 [50 52 54]
 [55 57 59]]


In [ ]:
!pip install scipy

In [ ]:
!pip install gradio

In [ ]:
import gradio as gr
def add_numbers(a,b):
  return a + b

demo = gr.Interface(fn=add_numbers, inputs=["number", "number"], outputs="text")
demo.launch(share= True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://8976ab5103ce9471ff.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
